name: QuickCommands
version: 1.2.4
description: Simplified versions of commands.
author: moltendorf
website: http://dev.bukkit.org/server-mods/moltendorf-quickcommands/
main: net.moltendorf.Bukkit.QuickCommands.Plugin
commands:
  colors:
    description: Display all the colors usable in chat.
    usage: /<command>
  durability:
    description: Check or set your tool's durability (-1 sets it to max).
    usage: /<command> [durability]
