name: QuickCommands
version: 1.2.2
description: Simplified versions of commands.
author: moltendorf
website: http://dev.bukkit.org/server-mods/moltendorf-quickcommands/
main: net.moltendorf.Bukkit.QuickCommands.Plugin
commands:
  colors:
    description: Display all the colors usable in chat.
    usage: /<command>
  durability:
    description: Check your tool's durability.
    usage: /<command>
