name: QuickCommands
version: 1.10.0
description: Simplified versions of commands.
author: moltendorf
website: http://dev.bukkit.org/server-mods/moltendorf-quickcommands/
main: net.moltendorf.Bukkit.QuickCommands.Plugin
commands:
  colors:
    description: Display all the colors usable in chat.
    usage: /<command>
  durability:
    description: Check or set your tool's durability (-1 sets it to max).
    usage: /<command> [durability]
  hide:
    description: Hide a player from another player.
    usage: /<command> [player] <from player>
  show:
    description: Show a player to another player.
    usage: /<command> [player] <to player>
  health:
    description: Configure a player's health.
    usage: /<command> <player> <max> [scale] [health]
  drop:
    description: Drop a player at a location.
    usage: /<command> <player> <x> <z>
  cleanup:
    description: Cleanup broken entities (currently only does arrows).
    usage: /<command>
permissions:
  quickcommands.drop:
    default: false
    description: Allows a player to use /drop.
